# Generated by Django 5.2 on 2025-04-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0002_alter_equipo_slug'),
        ('Redes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del jugador')),
                ('nickname', models.CharField(unique=True, verbose_name='Nickname en el juego')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='Equipos.equipo', verbose_name='Equipo del jugador')),
                ('redes', models.ManyToManyField(blank=True, related_name='jugador', to='Redes.redsocial')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
            },
        ),
    ]
