# Generated by Django 5.2 on 2025-04-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='redes',
        ),
    ]
