# Generated by Django 5.2 on 2025-04-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0002_alter_equipo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('primer_equipo_elegir', models.CharField(choices=[('equipo1', 'Equipo 1'), ('equipo2', 'Equipo 2')], max_length=10, verbose_name='Primer equipo en elegir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='Equipos.equipo', verbose_name='Equipo 1')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='Equipos.equipo', verbose_name='Equipo 2')),
            ],
        ),
    ]
