# Generated by Django 5.2 on 2025-04-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelTable(
            name='partida',
            table='Partidas',
        ),
    ]
