# Generated by Django 5.2 on 2025-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partidas', '0002_alter_partida_options_alter_partida_table'),
        ('Personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='personajes_baneados',
            field=models.ManyToManyField(blank=True, to='Personajes.personaje', verbose_name='Personajes baneados'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='primer_equipo_elegir',
            field=models.CharField(blank=True, choices=[('equipo1', 'Equipo 1'), ('equipo2', 'Equipo 2')], max_length=10, null=True, verbose_name='Primer equipo en elegir'),
        ),
    ]
