# Generated by Django 5.2 on 2025-04-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_alter_equipo_slug'),
        ('Partidas', '0003_partida_personajes_baneados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True, verbose_name='Primer equipo en elegir'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='Equipos.equipo', verbose_name='Equipo 1'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='Equipos.equipo', verbose_name='Equipo 2'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='primer_equipo_elegir',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True, verbose_name='Primer equipo en elegir'),
        ),
    ]
