# Generated by Django 5.2 on 2025-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partidas', '0004_partida_ganador_alter_partida_equipo1_and_more'),
        ('Personajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='ganador',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='personajes_baneados',
            field=models.ManyToManyField(blank=True, related_name='baneado_en', to='Personajes.personaje', verbose_name='Personajes baneados'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='primer_equipo_elegir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer equipo en elegir'),
        ),
    ]
