# Generated by Django 5.2 on 2025-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partidas', '0005_alter_partida_ganador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='ganador',
            field=models.CharField(blank=True, null=True, verbose_name='Ganador'),
        ),
    ]
