# Generated by Django 5.1.7 on 2025-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='jefe_equipo',
            field=models.BooleanField(default=False, verbose_name='Jefe equipo'),
        ),
    ]
