# Generated by Django 5.1.7 on 2025-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_alter_equipo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
