# Generated by Django 5.2 on 2025-04-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redes', '0001_initial'),
        ('RedesJugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redesjugador',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='redes_jugador', to='Redes.redsocial'),
        ),
    ]
