# Generated by Django 5.2 on 2025-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='personajes/'),
        ),
    ]
